services:
  - type: web
    name: influencerflow-api
    runtime: python
    buildCommand: |
      curl -LsSf https://astral.sh/uv/install.sh | sh
      source $HOME/.cargo/env
      uv pip install -r uv.lock || uv pip install -e .
    startCommand: uv run main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /api/v1/health
    autoDeploy: true
    plan: starter

  - type: worker
    name: influencerflow-worker
    runtime: python
    buildCommand: |
      curl -LsSf https://astral.sh/uv/install.sh | sh
      source $HOME/.cargo/env
      uv pip install -r uv.lock || uv pip install -e .
    startCommand: python -m app.worker
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: ENVIRONMENT
        value: production
    autoDeploy: true
    plan: starter

  - type: redis
    name: influencerflow-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free 